version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: medium-db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5056:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  nestjs-app:
    build:
      context: .
      target: development
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - /app/node_modules

volumes:
  pgdata: