openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - App
info:
  title: TIP Medium Service
  description: A Medium Service Provider
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas: {}
