openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - App
  /tag:
    get:
      operationId: TagController_findAllTags
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Tag
  /user/create:
    post:
      operationId: UserController_createUser
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - User
info:
  title: TIP Medium Service
  description: A Medium Service Provider
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas: {}
